### ISSUE TITLE
Support the rest of the Scratch API

### ISSUE THREAD

**Issue by GarboMuffin** [forkphorus/trampoline#13]
- users
 - studios
 - comments?
 - more?

**Comment by donnie9171** [comment]
Hi GarboMuffin, I'm trying to implement the Scratch search into ScratchGO and I noticed that the turbowarp proxy didn't include the search api. Is there any way I could contribute and add it? I just need the search project api to work.

**Comment by GarboMuffin** [comment]
I don't think we will be adding search support to our instance of trampoline as it is purpose built for TurboWarp & forkphorus

I don't know what "ScratchGO" is, but making your own proxy for the search API (or finding a way to communicate directly with Scratch if you aren't limited by web security) is not difficult

**Comment by donnie9171** [comment]
Thanks for the reply! I forked the trampoline code and added the search functionality after some tinkering. However, I still don't know how to host it on my own. Could you tell me how you set up the hosting for the turbowarp trampoline? 
btw [ScratchGO](http://scratchgo.app/) is a website I'm making to play Scratch games on mobile browsers. We had a brief exchange about it a few months ago about it when I introduced it to you ;)
